name: Build and Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          go mod tidy
          go build -o yafti-go -ldflags="-s -w" .

      - name: Create bundle
        run: |
          chmod +x install.sh
          tar -czf yafti-go-bundle.tar.gz yafti-go yafti.yml static install.sh

      - name: Create tagged release
        id: create_tagged_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            yafti-go-bundle.tar.gz
            yafti-go
          draft: false
          prerelease: false

      - name: Upload to latest release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          files: |
            yafti-go-bundle.tar.gz
            yafti-go
          draft: false
          prerelease: false
          tag_name: latest
