name: Build and Release

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'build-flatpak'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Install WebView dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Install flatpak-builder
        run: |
          sudo apt-get install -y flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Generate templ files
        run: go tool templ generate

      - name: Build binaries
        run: |
          go mod tidy
          go get github.com/webview/webview_go@latest
          go build -o yafti-go -ldflags="-s -w" .
          
          # Need to set PKG_CONFIG_PATH for WebKit 4.1
          export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/share/pkgconfig"
          # Force WebView to use webkit2gtk-4.1 instead of 4.0
          pkg-config --cflags -- gtk+-3.0 webkit2gtk-4.1 || true
          CGO_CFLAGS="`pkg-config --cflags gtk+-3.0 webkit2gtk-4.1`" \
          CGO_LDFLAGS="`pkg-config --libs gtk+-3.0 webkit2gtk-4.1`" \
          go build -o yafti-go-webview -ldflags="-s -w" ./cmd/webview
          
          # Create a wrapper script for the webview binary
          cat > yafti-go-webview-wrapper.sh << 'EOF'
          #!/bin/bash
          # Get the directory of this script
          DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
          cd "$DIR"
          # Run the webview binary
          export YAFTI_CONF="${DIR}/yafti.yml"
          ./yafti-go-webview
          EOF
          chmod +x yafti-go-webview-wrapper.sh

      - name: Generate timestamp for tag
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create and push latest tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/build-flatpak'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          TAG_NAME="latest-${{ steps.timestamp.outputs.timestamp }}"
          git tag -f $TAG_NAME
          git tag -f latest
          git push -f origin $TAG_NAME
          git push -f origin latest

      - name: Build Flatpak
        run: |
          sudo flatpak-builder --repo=repo --force-clean build-dir com.bazzite.Portal.yaml
          sudo flatpak build-bundle repo bazzite-portal.flatpak com.bazzite.Portal

      - name: Prepare webview release package
        run: |
          # Create a directory for the webview package
          mkdir -p yafti-webview-package
          cp yafti-go-webview yafti-webview-package/
          cp yafti-go-webview-wrapper.sh yafti-webview-package/
          cp -r static yafti-webview-package/
          cp yafti.yml yafti-webview-package/
          # Create a zip archive
          zip -r yafti-webview-package.zip yafti-webview-package

      - name: Create release with assets
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/build-flatpak'
        with:
          files: |
            yafti-go
            yafti-webview-package.zip
            bazzite-portal.flatpak
          draft: false
          prerelease: false
          tag_name: latest-${{ steps.timestamp.outputs.timestamp }}
          name: "Latest Build (${{ steps.timestamp.outputs.timestamp }})"

      - name: Create tagged release
        id: create_tagged_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/latest')
        with:
          files: |
            yafti-go
            yafti-webview-package.zip
            bazzite-portal.flatpak
          draft: false
          prerelease: false
